# Generated by Django 4.1.13 on 2024-01-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('imageProfile', models.ImageField(upload_to='product')),
                ('genre', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('isRegistered', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('produit_image', models.ImageField(upload_to='product')),
                ('produit_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireApp.compteuser')),
            ],
        ),
        migrations.AddField(
            model_name='compteuser',
            name='user_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireApp.user'),
        ),
    ]
