# Generated by Django 4.1.13 on 2024-01-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isRegistered',
        ),
    ]
